In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.feature_extraction import FeatureHasher

In [2]:
hasher_dict = FeatureHasher(n_features = 5, input_type = 'dict')

In [ ]:
random_dict = hasher_dict.fit_transform([{'a':1, 'b':2},
                                        {'a':0, 'c':5}])

In [4]:
random_dict

<2x5 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [5]:
random_dict.shape

(2, 5)

In [6]:
random_dict.toarray()

array([[ 1., -2.,  0.,  0.,  0.],
       [ 0.,  0., -5.,  0.,  0.]])

In [7]:
hasher_pair = FeatureHasher(n_features = 5, input_type = 'pair')

In [8]:
random_pair = hasher_pair.fit_transform([[('a', 1), ('b', 2)],
                                        [('a', 0), ('c', 5)]])

In [9]:
random_pair.toarray()

array([[ 1., -2.,  0.,  0.,  0.],
       [ 0.,  0., -5.,  0.,  0.]])

we cannot inverse transform the hashed data

In [10]:
text = ["Where there's a will, there's a way",
       "Look before you leap",
       "The early bird catches the worm",
       "Better late than never"]

In [11]:
hasher = FeatureHasher(n_features=8, input_type='string')

In [14]:
hashed_features = hasher.fit_transform(text)

In [15]:
print(hashed_features.shape)

(4, 8)


In [16]:
hashed_features.toarray()

array([[ 5.,  1.,  3., -3.,  2., -4., -1.,  4.],
       [ 4.,  0.,  1.,  5.,  1., -1.,  0.,  2.],
       [ 5.,  0.,  2.,  0.,  2., -6.,  1.,  3.],
       [ 3.,  2.,  2., -5., -1., -1., -1.,  5.]])