In [1]:
from sklearn.preprocessing import LabelBinarizer

import pandas as pd
import numpy as np

In [2]:
num_binarizer = LabelBinarizer()

In [3]:
num_binarizer.fit([2,3,4,5,3])

LabelBinarizer()

In [4]:
num_binarizer.classes_

array([2, 3, 4, 5])

In [5]:
num_binarizer.transform([2,3,4,5,3])

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0]])

In [7]:
# we can transform ither numbers as well

num_binarizer.transform([2,5])

array([[1, 0, 0, 0],
       [0, 0, 0, 1]])

In [8]:
temp_binarizer = LabelBinarizer(neg_label=-1, pos_label=1, sparse_output=False)

In [9]:
temperature = ['cold',
              'cold',
              'warm',
              'cold',
              'hot',
              'warm',
              'hot',
              'cold']

In [10]:
temp_binarizer.fit_transform(temperature)

array([[ 1, -1, -1],
       [ 1, -1, -1],
       [-1, -1,  1],
       [ 1, -1, -1],
       [-1,  1, -1],
       [-1, -1,  1],
       [-1,  1, -1],
       [ 1, -1, -1]])