In [1]:
from sklearn import preprocessing

import pandas as pd
import numpy as np

In [2]:
num_encoder = preprocessing.LabelEncoder()

In [3]:
num_encoder.fit([50,20,60,60])

LabelEncoder()

In [4]:
num_encoder.classes_

array([20, 50, 60])

In [5]:
num_encoder.transform([50,20,60,60])

array([1, 0, 2, 2], dtype=int64)

In [6]:
num_encoder.inverse_transform([1,0,2,2])

array([50, 20, 60, 60])

In [7]:
string_encoder = preprocessing.LabelEncoder()

In [8]:
string_encoder.fit(['cloudy','sunny','rainy','windy','cloudy'])

LabelEncoder()

In [9]:
string_encoder.classes_

array(['cloudy', 'rainy', 'sunny', 'windy'], dtype='<U6')

In [10]:
string_encoder.transform(['cloudy', 'rainy', 'sunny', 'windy'])

array([0, 1, 2, 3], dtype=int64)

In [13]:
data = pd.read_csv('datasets/exams.csv')

data

gender race/ethnicity parental level of education         lunch  \
0   female        group B          associate's degree      standard   
1   female        group B                 high school  free/reduced   
2   female        group D            some high school  free/reduced   
3     male        group A          associate's degree  free/reduced   
4   female        group E            some high school      standard   
..     ...            ...                         ...           ...   
95    male        group A          associate's degree      standard   
96  female        group E                some college      standard   
97    male        group B           bachelor's degree  free/reduced   
98    male        group B          associate's degree      standard   
99    male        group E            some high school  free/reduced   

   test preparation course  math score  reading score  writing score  
0                     none          55             61             58  
1                     none          59             70             66  
2                     none          17             18             26  
3                     none          63             61             58  
4                     none          70             80             79  
..                     ...         ...            ...            ...  
95                    none          80             81             73  
96                    none          81             86             84  
97                    none          67             74             72  
98               completed          67             62             64  
99                    none          67             59             57  

[100 rows x 8 columns]

In [14]:
data_encoder = preprocessing.LabelEncoder()

In [15]:
# this encodes all the colums at the same time
gender_le = data.apply(data_encoder.fit_transform)

In [17]:
gender_le

gender  race/ethnicity  parental level of education  lunch  \
0        0               1                            0      1   
1        0               1                            2      0   
2        0               3                            5      0   
3        1               0                            0      0   
4        0               4                            5      1   
..     ...             ...                          ...    ...   
95       1               0                            0      1   
96       0               4                            4      1   
97       1               1                            1      0   
98       1               1                            0      1   
99       1               4                            5      0   

    test preparation course  math score  reading score  writing score  
0                         1          14             17             16  
1                         1          18             26             23  
2                         1           0              0              0  
3                         1          22             17             16  
4                         1          29             36             35  
..                      ...         ...            ...            ...  
95                        1          36             37             29  
96                        1          37             41             39  
97                        1          26             30             28  
98                        0          26             18             21  
99                        1          26             16             15  

[100 rows x 8 columns]

In [19]:
data['gender'] = data_encoder.fit_transform(data.gender)

In [20]:
data

gender race/ethnicity parental level of education         lunch  \
0        0        group B          associate's degree      standard   
1        0        group B                 high school  free/reduced   
2        0        group D            some high school  free/reduced   
3        1        group A          associate's degree  free/reduced   
4        0        group E            some high school      standard   
..     ...            ...                         ...           ...   
95       1        group A          associate's degree      standard   
96       0        group E                some college      standard   
97       1        group B           bachelor's degree  free/reduced   
98       1        group B          associate's degree      standard   
99       1        group E            some high school  free/reduced   

   test preparation course  math score  reading score  writing score  
0                     none          55             61             58  
1                     none          59             70             66  
2                     none          17             18             26  
3                     none          63             61             58  
4                     none          70             80             79  
..                     ...         ...            ...            ...  
95                    none          80             81             73  
96                    none          81             86             84  
97                    none          67             74             72  
98               completed          67             62             64  
99                    none          67             59             57  

[100 rows x 8 columns]